# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170722_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='projects',
        ),
    ]
